# nixpacks.toml
# Especifica a Nixpacks que use PHP
packages = ["php"]
# Puedes especificar una versión de PHP si lo deseas, por ejemplo:
# packages = ["php82"] # Para PHP 8.2
# packages = ["php83"] # Para PHP 8.3
# Si no especificas una versión, intentará la última estable o la que mejor detecte.

[phases.setup]
# Aquí puedes añadir comandos para instalar extensiones de PHP si las necesitaras
# Por ejemplo, para instalar pdo_mysql si no viniera por defecto:
# apt_packages = ["php-mysql"] # Para sistemas basados en Debian/Ubuntu
# nix_packages = ["php82Packages.pdo_mysql"] # Para Nix/NixOS

[start]
# Este comando es el que se ejecutará para iniciar tu aplicación
# Debería coincidir con tu Procfile
cmd = "php -S 0.0.0.0:$PORT -t ."
