services:
  - type: web
    name: mi-app-web
    env: node  # o python, ruby, etc. según tu backend
    repo: https://github.com/usuario/tu-repo
    branch: main
    buildCommand: npm install  # o pip install -r requirements.txt, etc.
    startCommand: npm start     # cambia esto según tu framework
    plan: free
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mi-base-mysql
          property: connectionString

databases:
  - name: mi-base-mysql
    databaseName: basededatos
    user: usuario
    plan: free
    engine: mysql
