# render.yaml
# Este archivo define solo el servicio web para tu aplicación en Render.

services:
  # --- Servicio Web para tu aplicación PHP ---
  - type: web # Define que este es un servicio web
    name: pokemon-app # Nombre de tu servicio web en Render
    env: docker # Indica a Render que use tu Dockerfile para construir la imagen
    
    # La ruta a tu repositorio Git. Render lo detectará automáticamente si lo conectas.
    # repo: https://github.com/tu-usuario/tu-repositorio.git 
    # branch: main # La rama de tu repositorio a desplegar

    # El comando de construcción que Render ejecutará.
    # Si tienes un Dockerfile en la raíz, Render lo detectará automáticamente.
    # buildCommand: docker build -t pokemon-app . 

    # El comando de inicio que Render ejecutará para levantar tu aplicación.
    # Debe coincidir con el CMD de tu Dockerfile.
    startCommand: service php8.2-fpm start && nginx -g "daemon off;"

    # El puerto que tu aplicación expone (debe coincidir con EXPOSE en tu Dockerfile y listen en nginx-app.conf)
    port: 8080 

    # Variables de entorno para tu aplicación
    # Estas variables se añadirán manualmente después de crear la base de datos en Render.
    envVars:
      # Deja estas líneas comentadas o elimínalas por ahora si vas a añadirlas manualmente en el dashboard.
      # Si las dejas, asegúrate de que los valores coincidan con los de tu DB de Render.
      # - key: MYSQL_HOST
      #   value: "tu_host_mysql_de_render" 
      # - key: MYSQL_DATABASE
      #   value: "tu_nombre_db_de_render"
      # - key: MYSQL_USER
      #   value: "tu_usuario_db_de_render"
      # - key: MYSQL_PASSWORD
      #   value: "tu_password_db_de_render"
      # - key: MYSQL_PORT
      #   value: "3306" # O el puerto que Render te dé para MySQL
      
      # Opcional: Configuración de depuración para PHP (si no la pones en php.ini)
      # - key: PHP_DISPLAY_ERRORS
      #   value: "On"
      # - key: PHP_ERROR_REPORTING
      #   value: "E_ALL"
      # - key: PHP_LOG_ERRORS
      #   value: "On"
      # - key: PHP_ERROR_LOG
      #   value: "/dev/stderr" # Para que los errores aparezcan en los logs de Render

    # Opcional: Configuración de escalado o salud
    # healthCheckPath: /index.html # O una ruta de tu API que devuelva 200 OK
    # autoDeploy: true # Despliegue automático en cada push a la rama configurada
